portal/config/routes.rb
Rails.application.routes.draw do
  resources :listings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

portal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

portal/app/models/listing.rb
class Listing < ApplicationRecord
  include ActiveModel::Validations

  FIELDS      = %w[ Architecture Biology Business Computer_science Design Electrical_engineering Forensics Geology Health Illustration  ].freeze
  LEVELS      = %w[ Bachelor Master Doctorate ].freeze
  WORK_TYPES  = %w[ Internship Student_assistant Research Thesis Part_time ].freeze
  SALARY_OCCS = %w[ Hour Day Week Month  ].freeze

  validates :fields, :presence => true, :fields_valid => true
  validates :levels, :presence => true, :levels_valid => true
  validates :work_types, :presence => true, :work_types_valid => true
  validates :salary_occs, :presence => true, :salary_occs_valid => true
end

portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

portal/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
    render json: @listings
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
      render json: @listing
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      render json: @listing, status: :created
    else
      render json: @listing.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.json { render :show, status: :created, location: @listing }
      else
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    render json: :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title,  :logo_loc, :logo_dsc, fields: [], levels: [], work_types: [], locations: [], shifts: [])
    end
end

portal/app/helpers/application_helper.rb
module ApplicationHelper
end

portal/app/helpers/listings_helper.rb
module ListingsHelper
end

portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

portal/app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

portal/app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

portal/app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

portal/app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

portal/app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<%= @listing.title %>
<br>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>